# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea33329b8210f48eba05e7e44054fcbbfcdbc8c9cd59dc87e63cea33ddcbf14f5d7f3d34d7fd72c79e20d0864520001cb4ad2ef7f5bdc76eb2c68b79f6677fe0

test:
  secret_key_base: d1c519acfdebe49233b950ab33b17a4b31d324be3ec7a43af073e214f61bbfea2a6b6d5e84a40e8784b2258ab19ef3111293b0de9193e146e6085a2232fbbefd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
